vagrant_name = "ubuntu22"
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "private_network", type: "dhcp"
    config.vm.define vagrant_name

    config.vm.provider "virtualbox" do |v|
      v.name = vagrant_name
    end
    
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yaml"
    end

    config.vm.synced_folder ".", "/vagrant", disabled: false
end
