---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../../../projects/{{project_folder}}/"
  tags: "data"

- name: "Setup vulnerabilities with tasks"
  hosts: domain
  tasks:
    - include_role:
        name: "vulns/{{vuln}}"
      vars:
        vulns_vars: "{{ lab.hosts[dict_key].vulns_vars[vuln] | default({}) }}"
        domain: "{{lab.hosts[dict_key].domain}}"
        domain_username: "{{domain}}\\Administrator"
        domain_password: "{{lab.domains[domain].domain_password}}"
      loop: "{{lab.hosts[dict_key].vulns | default([]) }}"
      loop_control:
        loop_var: vuln

    - include_role:
        name: "ps"
      vars:
        script_path: "../../../projects/{{project_folder}}/scripts"
        ps_script: "{{script_path}}/{{item}}"
      loop: "{{lab.hosts[dict_key].scripts | default([]) }}"
