- name: playbook
  hosts: all
  become: true
  become_user: root
  tasks:
    - include_tasks: ./playbooks/vuln.yaml
    - include_tasks: ./playbooks/users.yaml
    - include_tasks: ./playbooks/flag.yaml
