Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-server"
    config.vm.network "private_network", type: "dhcp"

    # config.vm.provision "ansible" do |ansible|
    #   ansible.verbose = "v"
    #   ansible.playbook = "playbook.yaml"
    # end
    
    config.vm.synced_folder ".", "/vagrant", disabled: true
end